version: "3.8"

services: 
  static-file-server:
    image: nginx:alpine
    container_name: static_file_server
    restart: always
    volumes:
      - ./staticfiles:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4041:80"
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
