name: deploy
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: X64
    steps:
      - uses: actions/checkout@v2
      - name: stop container
        run: sudo docker compose rm -f -s -v
      - name: remove
        run: sudo docker image prune -a -f
      - name: build
        working-directory: ./backend
        run: sudo docker compose build
      - name: deploy
        run: sudo docker compose up -d
